### ISSUE TITLE
Can't push bytes objects to mock-amqp-server

### ISSUE THREAD

**Issue by jpmaligne** [weenect/mock-amqp-server#5] opened 2019-03-27 09:29 UTC
Reference to https://github.com/allan-simon/mock-amqp-server/issues/8

When calling :

`POST BASE_URL + '/add-message-on/' + EXCHANGE,`
with a body which contains serialized data,

I get an error, here is the stacktrace :

```
POST  b'/add-message-on/mail_sync.sync'
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 730, in _read_ready
    self._protocol.data_received(data)
  File "/service/http_protocol.py", line 37, in data_received
    self._data_received(data)
  File "/service/http_protocol.py", line 69, in _data_received
    self._on_post(self._target, event.data)
  File "/service/http_protocol.py", line 171, in _on_post
    full_message = json.loads(data.decode('utf-8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Whe can see json.loads is used to handle the request' body.

I used `pickle.dumps()` to serialize my data.

**Comment by jaymoulin** [comment] 2019-04-04 11:31
Not a bug of mock-amqp-server but a bug in the call.

`/add-message-on/` API is supposed to receive a JSON request which was not your case.

But message handling still needs to be utf-8 which causes a problem when you're using it with a rabbitmq client.

**Comment by jaymoulin** [comment] 2019-04-11 07:39
Fixed by https://github.com/allan-simon/mock-amqp-server/pull/10

**Closed as completed** 2019-04-15 07:52 UTC
Labels: bug, enhancement, good first issue
